### ISSUE TITLE
tentativa de fazer lista de quadros 

### ISSUE THREAD

**Issue by Psykozis** [notcc/texufpel#2]
Estou fazendo a dissertação utilizando este modelo, estou atualmente no ppg-spaf da ufpel, e preciso adicionar uma lista de quadros, que por serem de dados qualitativos não se enquadram em uma tabela.

Estou tentando de todas as formas, consegui através de long table adicionar o quadro, sem numeração, todas as soluções que encontro online são para utilização com abntex2. Gosto muito deste modelo, muito obrigado por disponibilizar! 

tentei da forma abaixo, que foi a única sem abntex2 que encontrei. mas só desformato tudo e não tenho êxito.
https://texblog.org/2008/07/13/define-your-own-list-of/

há algum meio mais simples? 
obrigado.

**Comment by notcc** [comment]
Olá, obrigado por utilizar a texufpel e pelo seu contato.
A lista de quadros não está na classe porque o modelo da UFPel não prevê isto.
Mas posso tentar ajudá-lo, poderias encaminhar exemplos do que queres, ou compartilhar no overleaf diretamente no meu email?
marilton @ inf.ufpel.edu.br
Abraços,
Marilton

**Comment by Psykozis** [comment]
Obrigado pela resposta! 
Devido a tua resposta, procurei nas normas da UFPel para ter embasamento e tive argumentação pra convencer meu orientador que segundo as mesmas, quadros são figuras, e assim são tratadas no texto. 
Obrigado!
